### PR TITLE
2-arg flatten to specify desired eltype

### LINKED ISSUE #12: Support `flatten(eltype, x)`?
The fact that `flatten(::Integer) -> Vector{Float64}` is kind of annoying, maybe we could propagate an `eltype` to make it clearer what the returned array should be? An alternative might be to recursively call `promote_type` as we go, but that seems like more work.

### PR DESCRIPTION
**Pull request by rofinn**
Also, updated equality checks in test_utils.jl

Closes #12

### CODE REVIEW

**Comment by willtebbutt** [comment]
I think I'm fine with this. Could we get a default that goes for `Float64` though please?

**Review by willtebbutt — APPROVED** [review]
I don't _think_ that this is breaking, so perhaps just bump the patch version?

**Comment by rofinn** [comment]
I suppose it could be breaking if you consider the test utils API as public, I guess those check are more relaxed if anything though.

**Comment by willtebbutt** [comment]
Hmm fair point. I'm happy with whatever you feel is appropriate.

**Comment by rofinn** [comment]
Okay, gonna merge and tag tomorrow. Simplified a couple of the tests, so that a larger `atol` is only used for lower precision tests. The reduced coverage seems to be caused by julia not recording the `@testset` lines in a function. Since the test suite isn't exported I've just opted to make it a patch release for now.

**Pull request merged**
