### PR TITLE
MassInstallAction: Install the GitHubActions workflow on this repository

### PR DESCRIPTION
**Pull request by fchorney**
This pull request sets up the GitHubActions workflow on this repository. cc: @fchorney

### CODE REVIEW

**Comment by willtebbutt** [comment]
@rofinn @fchorney does this PR superceed #7 , or should this be closed in favour of that one?

**Comment by rofinn** [comment]
I think #7 more accurately reflect our requirements for this repo, but I'd say we should merge that then update this PR accordingly. This PR will need to use the RSE slack token and correct julia versions/platforms anyways.

**Comment by fchorney** [comment]
Update the README, etc. I figure you guys will take care of this once #7 is merged in?

**Comment by willtebbutt** [comment]
@rofinn @fchorney who's looking after this PR now that #7 is merged?

**Comment by rofinn** [comment]
I was waiting for the conflicts to be resolved before re-reviewing.

**Comment by fchorney** [comment]
Ok I've rebased on master and made a few edits. Let me know if it looks good now.

**Comment by rofinn** [comment]
Any idea why Optim isn't getting installed on 1.0.5? I'd also be fine with dropping 1.0.5 since we don't use that release for anything this package is used for.

**Comment by fchorney** [comment]
Oh I see. So the tests are using their own `Project.toml` file for the test dependencies. This possibly isn't supported in 1.0.5?

**Comment by rofinn** [comment]
I think it's fine to just drop that release if you want?

**Comment by fchorney** [comment]
Sure, I've removed the job from the CI testing.

**Review by rofinn — APPROVED** [review]
LGTM, merging.

**Pull request merged**
